import Head from 'next/head'
import { JustifyBetween } from '@/components/twin'
import FilterButton from '@/components/Filters'
import { categery, colourStyles } from '@/constants/filters'
import ReactSelect from 'react-select'
import { MagnifyingGlassCircleIcon } from '@heroicons/react/20/solid'
import ActiveFilters from '@/components/Filters/ActiveFilters'
import UserProfile from '@/components/UsersProfile'
import useFetch from '@/hooks/useFetch'

export default function Home() {
  const { results, fetchData } = useFetch()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-5xl mx-auto mt-20">
        <JustifyBetween>
          <FilterButton />
          <div
            className="relative mt-2 flex  items-center justify-center"
            style={{ width: '65%' }}
          >
            <ReactSelect
              className="block w-2/12   text-gray-900 shadow-sm  border-0 max-[1050px]:hidden "
              options={categery}
              styles={colourStyles}
              placeholder="All"
              maxMenuHeight={500}
              // value={reactSelectCatagorySelectedOption}
              components={{
                IndicatorSeparator: () => null
              }}
            />

            <input
              type="search"
              name="search"
              id="search"
              onChange={(e) => fetchData(`${e.target.value} `)}
              placeholder="Search for mentors,creators,industry,sector..."
              className="block w-full border-x-0 border-y-0 h-10 bg-white rounded-md border-0 py-1.5 pl-3 pr-14 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:shadow-2xl focus:scale-105 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />

            <div className="absolute inset-y-0 right-0 flex py-1.5 pr-1.5">
              <button className="inline-flex items-center   border-0 px-1 font-sans text-xs text-gray-400 hover:bg-transparent ">
                <MagnifyingGlassCircleIcon className="h-8 w-8 text-gray-300 hover:text-blue-500 hover:bg-transparent hover:scale-105 rounded-full hover:shadow" />
              </button>
            </div>
          </div>
        </JustifyBetween>
        <ActiveFilters />
        {results && results.map(() => <p>hello</p>)}
        <UserProfile />
      </div>
    </div>
  )
}
